apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jenkinsproxy
  namespace: jenkins
spec:
  virtualhost:
    fqdn: jenkins.cornerstones.home
    tls:
      secretName: jenkinsproxy
  routes:
  - services:
    - name: jenkins
      port: 8180

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkinsproxy
  namespace: jenkins
spec:
  commonName: jenkins.cornerstones.home
  dnsNames:
  - jenkins.cornerstones.home
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: jenkinsproxy
