kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi