apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: n8nproxy
  namespace: n8n
spec:
  virtualhost:
    fqdn: n8n.cornerstones.local
    tls:
      secretName: n8nproxy
  routes:
  - services:
    - name: n8n
      port: 3000

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8nproxy
  namespace: n8n
spec:
  commonName: n8n.cornerstones.local
  dnsNames:
  - n8n.cornerstones.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: n8nproxy
