apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  releaseName: n8n
  chart:
    spec:
      chart: n8n
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    database:
      type: postgresdb
      postgresdb:
        host: postgresql.postgresql
    executions:
      timeout: 900
      maxTimeout: 900
      pruneData: true
    generic:
      timezone: UTC
    persistence:
      enabled: true
      existingClaim: n8n
      accessMode: ReadWriteOnce
      storageClass: managed-nfs-storage
      size: 1Gi