apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: contour
  namespace: contour
spec:
  interval: 1440m
  path: "./examples/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: contour
    namespace: flux-system
