apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: hassproxy
spec:
  virtualhost:
    fqdn: homeassistant.cornerstones.home
    tls:
      secretName: hassproxy
  routes:
  - services:
    - name: homeassistant-home-assistant
      port: 8123
  - conditions:
    - prefix: /api/websocket
    enableWebsockets: true
    services:
      - name: homeassistant-home-assistant
        port: 8123

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hassproxy
spec:
  commonName: homeassistant.cornerstones.home
  dnsNames:
  - homeassistant.cornerstones.home
  - hass.cornerstones.space
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: hassproxy
