apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: homeassistant
spec:
  rules:
  - host: homeassistant.cornerstones.local
    http:
      paths:
      - backend:
          serviceName: homeassistant-home-assistant
          servicePort: 8123
