apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: (Host(`control.local`) || Host(`worker01.local`) || Host(`worker02.local`)) && PathPrefix(`/hass`)
      kind: Rule
      services:
        - name: homeassistant-home-assistant
          port: 8123
