apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: postgresql
  namespace: postgresql
spec:
  providerRef:
    name: flux-system
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: postgresql
      namespace: postgresql