apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    image:
      registry: docker.io
      repository: postgres
      tag: latest
    persistence:
      primary:
        enabled: true
        storageClass: local-path
        accessModes:
          - ReadWriteOnce
