apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: promgrafanaproxy
  namespace: monitoring
spec:
  virtualhost:
    fqdn: grafana.cornerstones.local
    tls:
      secretName: promgrafanaproxy
  routes:
  - services:
    - name: kube-prometheus-stack-grafana
      port: 80

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: promgrafanaproxy
  namespace: monitoring
spec:
  commonName: grafana.cornerstones.local
  dnsNames:
  - grafana.cornerstones.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: promgrafanaproxy
