apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    namespaceOverride: "monitoring"
    defaultRules:
      create: true
      rules:
        kubeApiserverSlos: false
        kubeScheduler: false
    prometheus:
      prometheusSpec:
        externalUrl: "https://prometheus.cornerstones.local"
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
          smtp_auth_password: ""
          smtp_auth_username: ""
          smtp_from: ""
          smtp_smarthost: ""
        receivers:
        - name: pushover
          pushover_configs:
            - user_key: <PUSHOVER_USER_KEY>
              token: <PUSHOVER_API_TOKEN>
              expire: 30m
              message: '{{ template "pushover.cornerstones.text" . }}'
              priority: -1
              retry: 10m
              title: Cornerstones Pi Cluster
        - name: 'null'
        route:
          group_by:
          - job
          group_interval: 5m
          group_wait: 30s
          receiver: pushover
          repeat_interval: 12h
        templates:
        - /etc/alertmanager/config/*.tmpl
      templateFiles:
        pushover_1.tmpl: |-
          {{ define "cluster" }}{{ .ExternalURL | reReplaceAll ".*alertmanager\\.(.*)" "$1" }}{{ end }}
  
          {{ define "pushover.cornerstones.text" }}
          {{- $root := . -}}
          {{ range .Alerts }}
            <b>Alert:</b> {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            <b>Cluster:</b>  {{ template "cluster" $root }}
            <b>Description:</b> {{ .Annotations.description }}
            <b>Graph:</b> <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
            <b>Runbook:</b> <{{ .Annotations.runbook }}|:spiral_note_pad:>
            <b>Details:</b>
              {{ range .Labels.SortedPairs }} - <b>{{ .Name }}:</b> `{{ .Value }}`
              {{ end }}
          {{ end }}
          {{ end }}

