apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: adguardproxy
spec:
  virtualhost:
    fqdn: adguard.cornerstones.local
    tls:
      secretName: adguardproxy
  routes:
  - services:
    - name: adguard-adguard-home
      port: 3000

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguardproxy
spec:
  commonName: adguard.cornerstones.local
  dnsNames:
  - adguard.cornerstones.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: adguardproxy
