apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: adguardproxy
  namespace: adguard
spec:
  virtualhost:
    fqdn: adguard.cornerstones.home
    tls:
      secretName: adguardproxy
  routes:
  - services:
    - name: adguard-adguard-home
      port: 3000

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguardproxy
  namespace: adguard
spec:
  commonName: adguard.cornerstones.home
  dnsNames:
  - adguard.cornerstones.home
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: adguardproxy
