apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: adguard
spec:
  releaseName: adguard
  chart:
    spec:
      chart: adguard-home
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    service:
      dns-tcp:
        type: LoadBalancer
      dns-udp:
        type: LoadBalancer
    persistence:
      config:
        enabled: true
        storageClass: managed-nfs-storage
        existingClaim: adguardconfig
        size: 1Gi
        accessMode: ReadWriteOnce
        mountPath: /opt/adguardhome/conf
      data:
        enabled: true
        storageClass: managed-nfs-storage
        existingClaim: adguarddata
        size: 8Gi
        accessMode: ReadWriteOnce
        mountPath: /opt/adguardhome/work