apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: noderedproxy
  namespace: node-red
spec:
  virtualhost:
    fqdn: nodered.cornerstones.home
    tls:
      secretName: noderedproxy
  routes:
  - services:
    - name: node-red
      port: 1880
  - conditions:
    - prefix: /comms
    enableWebsockets: true
    services:
      - name: node-red
        port: 1880

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: noderedproxy
  namespace: node-red
spec:
  commonName: nodered.cornerstones.home
  dnsNames:
  - nodered.cornerstones.home
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: noderedproxy
