apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  releaseName: node-red
  chart:
    spec:
      chart: node-red
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    persistence:
      data:
        type: pvc
        existingClaim: node-red
        retain: true
        enabled: true
        mountPath: /data