apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: keycloakadminproxy
spec:
  virtualhost:
    fqdn: accessadmin.cornerstones.home
    tls:
      secretName: keycloakadminproxy

  - conditions:
    - prefix: /auth
    services:
      - name: keycloak-http
        port: 9990
        
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloakadminproxy
spec:
  commonName: accessadmin.cornerstones.home
  dnsNames:
  - accessadmin.cornerstones.home
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: keycloakadminproxy