apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: keycloakproxy
spec:
  virtualhost:
    fqdn: access.cornerstones.home
    tls:
      secretName: keycloakproxy
  routes:
  - conditions:
    - prefix: /
    services:
      - name: keycloak-http
        port: 9280
  - conditions:
    - prefix: /auth/admin/
    services:
      - name: keycloak-http
        port: 9990
 
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloakproxy
spec:
  commonName: access.cornerstones.home
  dnsNames:
  - access.cornerstones.home
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: keycloakproxy

 