apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - pvc.yaml
  - kc-user-sealed.json
  - kc-password-sealed.json
  - release.yaml
  - ingress.yaml
