apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    postgresql:
      enabled: false    # Disable the bundled Postgresql

    extraEnv: |
      - name: JAVA_OPTS
        value: >-
          -XX:+UseContainerSupport
          -XX:MaxRAMPercentage=50.0
          -Djava.net.preferIPv4Stack=true
          -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
          -Djava.awt.headless=true

      - name: DB_VENDOR
        value: postgres
      - name: DB_ADDR
        value: postgresql.postgresql.svc.cluster.local
      - name: DB_PORT
        value: "5432"
      - name: DB_DATABASE
        value: keycloak
      - name: DB_USER_FILE
        value: /secrets/db-creds/user
      - name: DB_PASSWORD_FILE
        value: /secrets/db-creds/password

    extraVolumeMounts: |
      - name: db-creds
        mountPath: /secrets/db-creds
        readOnly: true

    extraVolumes: |
      - name: db-creds
        secret:
          secretName: keycloak-db-creds