apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    sources: [service, ingress, contour-httpproxy]
    image:
      registry: docker.io
      repository: raspbernetes/external-dns
      tag: latest
    provider: pdns
    pdns:
      apiUrl: "http://192.168.1.62"
      apiPort: "8081"
      apiKey: "GarbageKey"    # To be updated after deployment
