apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    persistence:
      config:
        enabled: true
        existingClaim: homeassistant
        accessMode: ReadWriteOnce
        storageClass: managed-nfs-storage
        size: 8Gi
