apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: unifi
  namespace: unifi
spec:
  providerRef:
    name: flux-system
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: unifi
      namespace: unifi