apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: unifiproxy
  namespace: unifi
spec:
  virtualhost:
    fqdn: unifi.cornerstones.home
    tls:
      secretName: unifiproxy
  routes:
  - services:
    - name: unifi
      port: 8443

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifiproxy
  namespace: unifi
spec:
  commonName: unifi.cornerstones.home
  dnsNames:
  - unifi.cornerstones.home
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: unifiproxy
