apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: unifiproxy
  namespace: unifi
spec:
  virtualhost:
    fqdn: unifi.cornerstones.home
    tls:
      secretName: unifiproxy
  routes:
  - services:
    - name: unifi
      port: 8443
      protocol: tls
    - name: unifi
      port: 8080  
    timeoutPolicy:
      response: infinity
      idle: infinity
  - conditions:
    - prefix: /wss
    enableWebsockets: true
    timeoutPolicy:
      response: infinity
      idle: infinity
    services:
      - name: unifi
        port: 8443
        protocol: tls 

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifiproxy
  namespace: unifi
spec:
  commonName: unifi.cornerstones.home
  dnsNames:
  - unifi.cornerstones.home
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: unifiproxy
