apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: unifi-ingress
  namespace: unifi
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.cornerstones.local`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: unifi-gui
          port: 443
