apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvUnifi
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/Kubernetes/cornerstone/unifi
    server: 192.168.1.62
