apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  releaseName: unifi
  chart:
    spec:
      chart: unifi
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          external-dns.alpha.kubernetes.io/hostname: "unifi.cornerstones.home."
    service:
      udp:
        enabled: true
        type: LoadBalancer
        ports:
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP
    persistence:
      data:
        mountPath: /unifi
        enabled: true
        storageClass: managed-nfs-storage
        existingClaim: unifi
        size: 8Gi
        accessMode: ReadWriteOnce
