apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  releaseName: unifi
  chart:
    spec:
      chart: unifi
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    unifiedService:
      type: LoadBalancer
    guiService:
      type: LoadBalancer
    persistence:
      enabled: true
      storageClass: managed-nfs-storage
      existingClaim: unifi
      size: 8Gi
      accessMode: ReadWriteOnce
