apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mosquittoproxy
  namespace: mosquitto
spec:
  virtualhost:
    fqdn: mqtt.cornerstones.local
  routes:
  - services:
    - name: mosquitto
      port: 1883


