apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: contour
  namespace: flux-system
spec:
  interval: 1440m
  url: https://github.com/projectcontour/contour-operator.git