kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik
  namespace: traefik
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi