apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: heimdallproxy
  namespace: heimdall
spec:
  virtualhost:
    fqdn: apps.cornerstones.local
    tls:
      secretName: heimdallproxy
  routes:
  - services:
    - name: heimdall
      port: 80

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heimdallproxy
  namespace: heimdall
spec:
  commonName: apps.cornerstones.local
  dnsNames:
  - apps.cornerstones.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: heimdallproxy
