kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: postgresql
  name: postgresql
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
