apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    architecture: standalone
    global:
      storageClass: managed-nfs-storage
    metrics:
      enabled: false 
    persistence:
      enabled: true
      storageClass: managed-nfs-storage
      existingClaim: postgresql
      size: 20Gi
      accessModes:
        - ReadWriteOnce
 