kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: trow
  name: trow
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
