apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trow
  namespace: trow
spec:
  releaseName: trow
  chart:
    spec:
      chart: trow
      sourceRef:
        kind: HelmRepository
        name: trow
        namespace: flux-system
  interval: 1440m
  install:
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
    volumeClaim:
      storageClass: managed-nfs-storage
      existingClaim: trow    
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 256Gi